### ISSUE TITLE
lat and lon are returned as strings instead of numbers

### ISSUE THREAD

**Issue by okdistribute** [noffle/hyperdb-osm#4]
In osm-p2p-db, lat and lon are returned as numbers but in hyperdb-osm they are returned as strings.

**Comment by hackergrrl** [comment]
True! This was intentional, though I'm not too thrilled about it. With osm-p2p-db we'd run into situations where Javascript's max-int (51 bits) would cause problems and you'd store a number as something but it'd get stored and returned as something else. Strings felt like a good solution because they guarantee that what you call `db#put` with is exactly what is stored and returned.

**Comment by okdistribute** [comment]
OK Cool!
